name: apokalupsis_lgn2
description: "A new Flutter project."
publish_to: 'none'

version: 2.0.0+2

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.3.0
  cloud_firestore: ^5.3.0
  video_player: ^2.5.2
  firebase_storage: ^12.1.3
  file_picker: ^8.0.7
  logger: ^2.4.0
  image_cropper: ^3.0.0
  image_picker: ^0.8.4+4
  logging: ^1.0.2
  intl: ^0.17.0
  shared_preferences: ^2.0.7 
  cached_network_image: ^3.1.0
  uuid: ^3.0.6
  photo_view: ^0.14.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.0.0
  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#000000"
  image: assets/images/splash.png
  android: true
  ios: true
  web: false

flutter:
  uses-material-design: true
  assets:
    - assets/images/resized_banner_logo_2.png
    - assets/images/resized_banner_logo.png
    - assets/images/giving_1.png
    - assets/images/tribe.png
    - assets/images/contact.png
    - assets/images/ic_launcher_mdpi.png
    - assets/images/ic_launcher_hdpi.png
    - assets/images/ic_launcher_xhdpi.png
    - assets/images/ic_launcher_xxhdpi.png
    - assets/images/ic_launcher_xxxhdpi.png
    - assets/images/splash.png
